databases:
  - name: campuslf-db
    plan: free
    databaseName: campuslf
    user: campuslf

services:
  - type: web
    name: campus-lost-and-found
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn lostandfound.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campuslf-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.0"
